###############################################################
# Copyright (c) 2021, 2023 Contributors to the CatenaX (ng) GitHub Organisation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Apache License, Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0.
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.
#
# SPDX-License-Identifier: Apache-2.0
###############################################################

reportportal:
  uat:
    superadminInitPasswd:
      auto: false
      password: "<path:portal/data/reportportal/reportportal#password>"
  ingress:
    enable: true
    annotations:
      kubernetes.io/ingress.class: nginx
    usedomainname: true
    hosts:
      - portal-reportportal.dev.demo.catena-x.net
    tls:
      - hosts:
          - portal-reportportal.dev.demo.catena-x.net
        secretName: "tls-secret"
  rabbitmq:
    endpoint:
      address: reportportal-rabbitmq
      user: rabbitmq
      apiuser: rabbitmq
      password: "<path:portal/data/reportportal/rabbitmq#rabbitmqPassword>"
  postgresql:
    endpoint:
      address: reportportal-postgresql
      password: "<path:portal/data/reportportal/postgresql#password>"
  elasticsearch:
    endpoint: http://reportportal-elasticsearch:9200
    password: "<path:portal/data/reportportal/elasticsearch#password>"
  minio:
    endpoint: http://reportportal-minio:9000
    endpointshort: reportportal-minio:9000
    accesskey: "<path:portal/data/reportportal/minio#rootUser>"
    secretkey: "<path:portal/data/reportportal/minio#rootPassword>"
