apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: portal-pgadmin4-rc
spec:
  destination:
    namespace: product-iam
    server: 'https://kubernetes.default.svc'
  source:
    path: charts/pgadmin4
    repoURL: 'https://github.com/catenax-ng/product-portal-tools.git'
    targetRevision: helm-environments
    plugin:
      env:
        - name: AVP_SECRET
          value: vault-secret
        - name: helm_args
          value: '-f values.yaml -f envs/values-rc.yaml'
  project: project-portal
