apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: portal-upgrade-pgadmin4
spec:
  destination:
    namespace: product-iam
    server: 'https://kubernetes.default.svc'
  source:
    path: charts/pgadmin4
    repoURL: 'https://github.com/catenax-ng/product-portal-tools.git'
    targetRevision: upgrade/int-env
    plugin:
      env:
        - name: AVP_SECRET
          value: vault-secret
        - name: helm_args
          value: '-f values.yaml -f envs/values-upgrade.yaml'
  project: project-portal
