apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: reportportal-minio
spec:
  destination:
    namespace: product-portal
    server: 'https://kubernetes.default.svc'
  source:
    path: charts/reportportal/minio
    repoURL: 'https://github.com/catenax-ng/product-portal-tools.git'
    targetRevision: main
    plugin:
      env:
        - name: AVP_SECRET
          value: vault-secret
  project: project-portal
