apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.postgresql.auth.existingSecret }}
  namespace: {{ .Release.Namespace }}
stringData:
  #  10 characters
  postgres-password: {{ .Values.secrets.auth.existingSecret.postgresPassword | default ( randAlphaNum 16 | quote ) }}
  #  32 characters
  password: {{ .Values.secrets.auth.existingSecret.password | default ( randAlphaNum 16 | quote ) }}