apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.rabbitmq.auth.existingPasswordSecret }}
  namespace: {{ .Release.Namespace }}
stringData:
  #  10 characters
  rabbitmq-password: {{ .Values.secrets.auth.existingSecret.rabbitmqPassword | default ( randAlphaNum 10 | quote ) }}
  #  32 characters
  rabbitmq-erlang-cookie: {{ .Values.secrets.auth.existingSecret.rabbitmqErlangCookie | default ( randAlphaNum 32 | quote ) }}