apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.minio.global.minio.existingSecret }}
  namespace: {{ .Release.Namespace }}
stringData:
  #  10 characters
  access-key: {{ .Values.secrets.auth.existingSecret.rootUser | default ( randAlphaNum 32 | quote ) }}
  #  32 characters
  secret-key: {{ .Values.secrets.auth.existingSecret.rootPassword | default ( randAlphaNum 32 | quote ) }}