apiVersion: v1
kind: Secret
metadata:
  name: secret-postgresql
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  password: {{ .Values.reportportal.postgresql.SecretName | default ( randAlphaNum 32 | quote ) }}
