apiVersion: v1
kind: Secret
metadata:
  name: secretkey-minio
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  password: {{ .Values.reportportal.minio.secretkey | default ( randAlphaNum 32 | quote ) }}
