apiVersion: v1
kind: Secret
metadata:
  name: secret-minio
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  password: {{ .Values.reportportal.minio.secretName | default ( randAlphaNum 32 | quote ) }}
